# Import the theme
theme: jekyll-theme-chirpy

# Site language & timezone
lang: tr
timezone: Europe/Skopje

# SEO
title: realkage
tagline: CTF Writeups • Bug Bounty Notes • Web Security
description: >-
  CTF writeup’larım, bug bounty notlarım ve web güvenliği üzerine teknik içerikler.
  Eğitim amaçlıdır; yalnızca yetkili ve izinli ortamlarda uygulanmalıdır.

# GitHub Pages URL
url: "https://realkage.github.io"
baseurl: ""

github:
  username: realkage

social:
  name: realkage
  email: ""
  links:
    - https://github.com/realkage
    - https://www.linkedin.com/in/basriakkaya/
    - https://tryhackme.com/p/realkage
    - https://bugcrowd.com/h/realkage

# Avatar (senin dosyan JPG)
avatar: /assets/img/avatar.jpg

# Theme mode:
# Boş bırak → sistem ayarına göre light/dark + toggle aktif
theme_mode:
